project:
  type: website
  output-dir: docs

website:
  title: "B3108 speed anlaysis"
  navbar:
    left:
      - href: index.qmd
        text: Summary
      - href: journey_time.qmd
        text: Time
      - href: noise.qmd
        text: Noise
      - href: other.qmd
        text: Other
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



